### ISSUE TITLE
./include/firewall.hpp:8:10: fatal error: 'eosiolib/currency.hpp' file not found

### ISSUE THREAD

**Issue by EnjoyAndroid** [firewall-x/contract#2]
./include/firewall.hpp:8:10: fatal error: 'eosiolib/currency.hpp' file not found
#include <eosiolib/currency.hpp>

**Comment by ohJohanZ** [comment]
> ./include/firewall.hpp:8:10: fatal error: 'eosiolib/currency.hpp' file not found
> #include <eosiolib/currency.hpp>

You should use eosio.cdt 1.2.1 or lesser version to build your contract, we are working on another sdk for eosio.cdt 1.3.0 or greater compiler, and we will commit it in a few days.

**Comment by lixiaodong** [comment]
eosio-cpp version 1.2.1
also have this issue.
