### ISSUE TITLE
how can i use it in kylin testnet?

### ISSUE THREAD

**Issue by lixiaodong** [firewall-x/contract#3]
i think the follow steps i should do :

1. deploy the firewall contract to kylin testnet
2.register the test account

Is that right ?

**Comment by ohJohanZ** [comment]
> i think the follow steps i should do :
> 
> 1. deploy the firewall contract to kylin testnet
>    2.register the test account
> 
> Is that right ?

We have set up a firewall contract in cryptokylin testnet already, what you should do is register your dapp contract. follow:
1. Open "https://firewallx.io/console/"
2. Signout (if you have sign in)-> Switch Net to "cryptokylin testnet" -> signin with a manage account
3. Click button "Add DApp", you will find a transfer command, just run it with cleos or do it with your eos wallet. Do not change the memo format.
4. include sdk
